### ISSUE TITLE
Highlight potential license issues / copying of code

### ISSUE THREAD

**Issue by Standard8** [cleidigh/ThunderKdB#10]
Since this site links to different extensions, all with different licenses, I think there should be some sort of warning/reminder to add-on developers to respect licenses when looking at code.

Straight copying of code/ideas from one license to another could potentially cause issues in future.

**Comment by cleidigh** [comment]
@Standard8 
I think that's a good idea.  I made sure I to have the exact extension license called out on the extension details page.  Adding a general note perhaps my current index for now.

**Comment by cleidigh** [comment]
Added licensing note to top index
