### ISSUE TITLE
have comment link on front page

### ISSUE THREAD

**Issue by opto** [cleidigh/ThunderKdB#13]
for a moment, I was wondering how to send in comments. Then I remembered the code should have issues.

maybe put a link onto the front page for those who do not know

**Comment by cleidigh** [comment]
O
I don't know why did not see this before, GH notifications??
Do you mean to add a link on the index page to the repository issues?
That's a good one.

**Comment by cleidigh** [comment]
Done
![image](https://user-images.githubusercontent.com/25272315/70203473-07ab1680-16eb-11ea-8479-3a9f9d5027e2.png)
