### ISSUE TITLE
xpiLib search broken

### ISSUE THREAD

**Issue by opto** [cleidigh/ThunderKdB#18]
I searched for 'attachment column' and got results from all over the world, outside of the repo

**Comment by cleidigh** [comment]
@opto 
I just got a chance to look at this.  Thanks!
What other options did you use? 
I just tried
"attachment column" (including quotes)
with 68 extensions and got 8 results all within library
and the other things I should know?
@cleidigh

**Comment by cleidigh** [comment]
@opto 
I think I got it. If NO compatibility selections is checked, it looks like it looks everywhere.
Will fix tomorrow.
I also have to find the time to do the other additions you suggested, I am swamped!

Thanks for catching this, I hope the library continues  to be useful
@cleidigh

**Comment by cleidigh** [comment]
@opto 
stayed up late, fixed the all  button now set as default

**Comment by cleidigh** [comment]
Fixed
