### ISSUE TITLE
How do you get the Thunderbird version info in background.js?

### ISSUE THREAD

**Issue by eyalroz** [cleidigh/ThunderKdB#24]
For "MailExtensions", nothing is overlayed based on your extension. Instead, a "background script", listed in manifest.json, is run.

In that script, you don't have access to all sorts of facilities you're used to in Thunderbird proper.

Specifically, how do you get the Thunderbird version info in there?

Please provide a concrete snippet of code.

**Comment by eyalroz** [comment]
There's a function which gets you the version information, named [`browser.runtime.getBrowserInfo()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/Runtime/getBrowserInfo). However - it's not trivial to use it, because it is a Javascript [**asynchronous function**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function). Many of us extension authors are not used to seeing these, since they're a relative recent feature of Javascript - and thus TB internals didn't expose anything to us involving it.

Unfortunately (?), to call an async function your own code must be asynchronous too, or at least - sort-of.

Suppose your `background.js` script has the following:
```
  let version = "71.2";
messenger.doSomethingWith(version);
```
this code, at file scope, cannot call async functions. So, we'll wrap it in a function, and invoke it right after defining it - a coding pattern called IIFE, or "Immediately-Inoked Function Expression" - and we'll also make that function async. This is what it looks like:
```
(async function() {
  let version = "71.2";
  messenger.doSomethingWith(version);
})()
```
The function is defined within the parenthesized expression, and we then use an invoke operator - a pair of parentheses following it. Note the `async` keyword. Finally, let's use that `getBrowserInfo()` function I mentioned:

```
(async function() {
  let browserInfo = await browser.runtime.getBrowserInfo();
  let version = browserInfo.version;
  messenger.doSomethingWith(version);
})()
```

**Comment by jobisoft** [comment]
You can also use the `.then` method of the returned Promise, if you do not want to adapt to the new async/await concept:

```
browser.runtime.getBrowserInfo().then(doSomething);
```

This will call the `doSomething` callback function with a single parameter: the return value of `getBrowserInfo()`:

```
function doSomething(browserInfo) {
   console.log(browserInfo)
}
```

A more modern way to define the callback function is to use an anonymous arrow function:

```
browser.runtime.getBrowserInfo().then((browserInfo) => {
  console.log(browserInfo);
});
```

However, I really like the async/await concept, as it produces sequential but still async code, which is very easy to read. I therefore always wrap my background in an async main function:

```
(async function () {
  // all my background stuff goes here
  
  // ...

  let browserInfo = await browser.runtime.getBrowserInfo();
  console.log(browserInfo)
  
  // ...
})()
```

**Comment by eyalroz** [comment]
> ... I therefore always wrap my background in an async main function

Yup, that was what I [decided to go with](https://github.com/eyalroz/removedupes/blob/master/src/background.js) as well.
