### ISSUE TITLE
The KDB entry for for gdata-provider doesn't list its experiment

### ISSUE THREAD

**Issue by eyalroz** [cleidigh/ThunderKdB#25]
Here: https://cleidigh.github.io/ThunderKdB/xall/extension-list-all.html

It suggests that gdata-provider doesn't use a 'WebExperiment', while in fact, it does:

https://github.com/kewisch/gdata-provider/blob/master/src/api/

(even though its use is limited).

**Comment by jobisoft** [comment]
The new lists on https://thundernest.github.io/add-on-reports/atn-tb91.html show that in better detail.
