### ISSUE TITLE
How to search for web extension events references

### ISSUE THREAD

**Issue by opto** [cleidigh/ThunderKdB#28]
I wanted to search for examples of webextension api events. They are declared as "events":

Unfortunately, I cannot use that as a search string: results are for returned 'events', not for '"events":'.

any workaround?

thanks,
Klaus

**Comment by cleidigh** [comment]
hey Klaus
Hope all is well
unfortunately as absurd as it sounds gh searches ignore most punctuation characters absolutely absurd no!  for one trick I try to use two words that mostly appeared together so I will experiment what might work and post shortly
Christopher

**Comment by cleidigh** [comment]
K
I think the closest trick is the following
use two words no punctuation:
 schema events
then filter for manifest.json

I am sure it would be helpful to have more source lines for each entry found
I remember you asking for this, gh does not give this as an option unfortunately
let me know if this works
![image](https://user-images.githubusercontent.com/25272315/110523928-c4570900-80e0-11eb-914d-090e88643b11.png)

![image](https://user-images.githubusercontent.com/25272315/110524035-e2246e00-80e0-11eb-989a-64b5711b839d.png)

**Comment by opto** [comment]
thanks Christopher, that helped and did it.

Klaus
