### ISSUE TITLE
How do I obtain the body of a message, given its URI?

### ISSUE THREAD

**Issue by eyalroz** [cleidigh/ThunderKdB#43]
In my extension, I have some very old code which using sync-stream-listener and scriptableinputstream to read the body of a message, given its URI. Since that code was in fashion, sync-stream-listener has been deprecated... [Mozilla bug 1800606](https://bugzilla.mozilla.org/show_bug.cgi?id=1800606). How should I obtain a message's body these days?

**Comment by cleidigh** [comment]
@eyalroz 
I think you want the wext API call getFull, not sure what is the best way to get uri to id.
@cleidigh

**Comment by eyalroz** [comment]
@cleidigh : I'm not looking for a WE wrapper, I'm asking how I do it in regular TB JS code / in a regular extension. Right now, I'm doing it [this way](https://github.com/eyalroz/removedupes/blob/development/src/chrome/content/removedupes.js#L629), with a stream listener etc. I was hoping maybe over the years the underlying infrastructure had evolved so that once can synchronously get a message body with relative ease...

**Comment by cleidigh** [comment]
@eyalroz 
That is the new (and easy}, don't know alternative.
@cleidigh

**Comment by eyalroz** [comment]
Thanks... too bad, I hoped 15 years had seen some work on this.
