### ISSUE TITLE
broken link 404

### ISSUE THREAD

**Issue by opto** [cleidigh/ThunderKdB#9]
https://github.com/cleidigh/ThunderKdB/blob/master/extensions-all/exts-tb68-comp/extension-list-tb68.md

**Comment by cleidigh** [comment]
@opto 
From which page did you get that link?  One thing to understand that I briefly described in the post notes:  The code exists in the main repository https://github.com/cleidigh/ThunderKdB
which is different than the GH pages "website".  The link you mentioned above is a link to the markdown file which is actually only correctly served when viewed through Pages.
I have to make indexes for both sides so it's easy to go between them.  I'm guessing I have an old blank on the main repository side.  If you want to get to either the reports for the search use the Pages link:
https://cleidigh.github.io/ThunderKdB/
Notice Pages get served under github.io
that's a way to tell the difference from the URL

**Comment by opto** [comment]
it is the extensions link in the readme on thi age:
https://github.com/cleidigh/ThunderKdB

**Comment by cleidigh** [comment]
Yep, that's what I thought  I started using MarkDown in the beginning but you cannot have JavaScript with that so I brought up a pages site which was totally new to me.  I have two make the read me point to the pages index.  will go and fix now...
did you see my comments on searching for dialog?

**Comment by cleidigh** [comment]
just pushed the fix
now if you're on the main repository side you can go to the root readme.md and it will get you back to the main index on the pages side.  it's a little bit weird but that's how it works

**Comment by cleidigh** [comment]
Fixed
